<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>13.0</LangVersion>
    <AssemblyName>TeamUp</AssemblyName>
    <RootNamespace>Ronvotri.TeamUp</RootNamespace>
    <ProjectVersion>0.2.0-alpha.6.7.44.21</ProjectVersion>
    <Version>$(ProjectVersion)</Version>
    <EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>
</Project>